# Generated by Django 3.2.15 on 2022-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='link',
            field=models.CharField(default='sfsdfa', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
