# Generated by Django 3.2.15 on 2022-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_cars_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, default='pics/logo.png', null=True, upload_to='pics/'),
        ),
    ]
